### PR TITLE
Change font to Poppins

### PR DESCRIPTION
**Pull request by corydalis10**
@cuavas Changed font to Poppins for better readability!

화면 캡처 2024-09-06 210057

### CODE REVIEW

**Comment by cuavas** [comment]
Sorry, but that looks awful.  Just in the first line, the uppercase “S” is top-heavy, the horizontal bar on the lowercase “e” is seriously underweight, the dot on the lowercase “i” is disproportionately large, the vertical on the lowercase “f” looks bold compared to the lowercase “l”…  Whoever made this font needs to go back to typography school.

**Comment by corydalis10** [comment]
@cuavas LOL 🤣

**Comment by rivercory** [comment]
@cuavas I think we need to change the font, even if it's not this one!
Please search the websites below or other resources and let me know what you think!
https://fonts.google.com/

**Comment by ghost** [comment]
The current font is fine as it is. What are **specifically** your problems with how you read it?

**Pull request closed without merging**
