### PR TITLE
Correct Exidy and Kauffman typos.

### PR DESCRIPTION
**Pull request by hackbar**
Obituary with correct spelling: https://www.gamasutra.com/view/news/247873/Obituary_Exidy_founder_Pete_Kauffman.php

### CODE REVIEW

**Comment by stilett0** [comment]
"Xidy" is actually not a typo.

From my recollections: sometime around 2007, Harold Ray "Pete" Kauffman either reformed or renamed Exidy as Xidy, Inc. to handle the future licensing of Exidy software and perhaps pursue some new software development.

So... yes, we're actually thanking "Xidy, Inc."

**Comment by stilett0** [comment]
@hackbar I'm afraid I don't have too much evidence for my allegation so far but maybe you'll accept his (now defunct but still available) LinkedIn page, which spells his last name correctly but his company name in the "newer" fashion I mentioned earlier: https://www.linkedin.com/in/pete-kauffman-19266337/

**Comment by rb6502** [comment]
Yeah, the "Xidy" spelling was a successor company for copyright purposes.  The last name should be corrected, but "Xidy" is correct.

**Comment by hackbar** [comment]
Good point. I've clarified he was the founder of Exidy, since that's pretty important to mention.

PTAL.

**Comment by hackbar** [comment]
Ping?

**Comment by stilett0** [comment]
Fine by me. Thanks for following up!

**Pull request merged**
