### PR TITLE
Updates for 0.194

### PR DESCRIPTION
**Pull request by NULUSIOS**
Update for 0.194 and some cleanup.

### CODE REVIEW

**Comment by stilett0** [comment]
Something is quite wrong with this pull request, the diff isn't clean. My current theory is that you used the "Upload Files" button on Github.com to create your pull request, and uploaded history.php and full_mame_history.html through the Upload Files interface.

Example:
Yours: https://github.com/mamedev/www.mamedev.org/pull/17/files/72db711dfd2086398be153fce6d93f8504df0adf..3d2afa00e187fb0e59aab3fccea93afa3b1003c5

Mine, if I separate out all your changes: https://github.com/stilett0/www.mamedev.org/commit/3645ea8bffa278928af9642930d0129663317037

My suggestion is that instead of doing that, that you clone the repo and then use a git client like Github Desktop on Windows to download your clone locally, then make your changes, then commit to your clone, then submit the pull request.

If you don't mind, I can submit a pull request of my changes, and credit you.z
Otherwise, feel free to close this PR and create a new one following my suggestion.

PS. Also, it's "Archimedes", not "Archimenes". Typo.

**Comment by NULUSIOS** [comment]
Yes this is what happened. I am currently rebuilding my computer so I did what I could "quick n' dirty".
No git client yet on new setup.

Thanks for the fix. Fixing in source in 5.
Make sure it is fixed in both
full_mame_history.html and history.php
Yes please submit as needed, no worries.
Thanks.

**Comment by stilett0** [comment]
Committed https://github.com/mamedev/www.mamedev.org/pull/18.

Closing this one.

**Comment by stilett0** [comment]
@NULUSIOS For future work: there was talk in one of the MAME chatrooms about a week ago amongst devs regarding your work.

This inspired a number of intentional removals of MAME release descriptions for "noteworthiness" and adjustments to descriptions.

This then caused me to cross compare the old "MAME Milestones" page on the wiki with newer changes which had recently been made with the history.php and full_mame_history.html files.
http://wiki.mamedev.org/index.php?title=MAME_Milestones&action=history

Everything is synced up as of this writing, but some people are still editing the wiki version of the history page. I will be keeping an eye on this for the next time there's an update, and I suggest you do the same.

The next time you go to make changes, please base your changes off of the latest version of the files, in the repo.

**Pull request closed without merging**
